apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-config.yaml

replicas:
  - name: app
    count: 1

images:
  - name: workshop-app
    newName: image-registry.openshift-image-registry.svc:5000/<user>-devspaces/workshop-app # Project名は各自で設定してください
    newTag: latest
