apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: DB_URL
              value: jdbc:postgresql://prod-db:5432/workshop
