apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: workshop-app
    component: db
type: Opaque
stringData:
  database-user: workshop
  database-password: workshop-pass
  database-name: workshop
