apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - app-route.yaml
  - app-configmap.yaml
  - db-deployment.yaml
  - db-service.yaml
  - db-secret.yaml
  - db-pvc.yaml

commonLabels:
  workshop: openshift-basic

images:
  - name: workshop-app
    newName: image-registry.openshift-image-registry.svc:5000/NAMESPACE/workshop-app
    newTag: latest
